# notion_client.py - All Notion API logic
import requests
from datetime import datetime
from config import NOTION_API_KEY, NOTION_DATABASE_ID


NOTION_API_URL = "https://api.notion.com/v1/pages"
NOTION_VERSION = "2022-06-28"


def get_headers() -> dict:
    """Return Notion API headers."""
    return {
        "Authorization": f"Bearer {NOTION_API_KEY}",
        "Content-Type": "application/json",
        "Notion-Version": NOTION_VERSION
    }


def create_note(data: dict, source_url: str = None) -> dict:
    """Create a new note page in Notion database."""
    
    properties = {
        "Name": {
            "title": [{"text": {"content": data.get("title", "Untitled")}}]
        }
    }
    
    # Build page content blocks
    children = [
        # Header with emoji
        {
            "object": "block",
            "type": "callout",
            "callout": {
                "rich_text": [{"type": "text", "text": {"content": f"📚 {data.get('field', 'General')} • Difficulty: {data.get('difficulty', 'Medium')}"}}],
                "icon": {"emoji": "🎯"}
            }
        },
        # Divider
        {"object": "block", "type": "divider", "divider": {}},
        # Summary section
        {
            "object": "block",
            "type": "heading_2",
            "heading_2": {
                "rich_text": [{"type": "text", "text": {"content": "📝 Summary"}}]
            }
        },
        {
            "object": "block",
            "type": "paragraph",
            "paragraph": {
                "rich_text": [{"type": "text", "text": {"content": data.get("summary", "")}}]
            }
        },
        # Divider
        {"object": "block", "type": "divider", "divider": {}},
        # Key Concepts section
        {
            "object": "block",
            "type": "heading_2",
            "heading_2": {
                "rich_text": [{"type": "text", "text": {"content": "🔑 Key Concepts"}}]
            }
        }
    ]
    
    # Add each concept as a bullet point
    for concept in data.get("key_concepts", []):
        children.append({
            "object": "block",
            "type": "bulleted_list_item",
            "bulleted_list_item": {
                "rich_text": [{"type": "text", "text": {"content": concept}}]
            }
        })
    
    # Add source URL if provided
    if source_url:
        children.extend([
            {"object": "block", "type": "divider", "divider": {}},
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {
                    "rich_text": [{"type": "text", "text": {"content": "🔗 Source"}}]
                }
            },
            {
                "object": "block",
                "type": "bookmark",
                "bookmark": {"url": source_url}
            }
        ])
    
    # Add timestamp
    children.extend([
        {"object": "block", "type": "divider", "divider": {}},
        {
            "object": "block",
            "type": "paragraph",
            "paragraph": {
                "rich_text": [{
                    "type": "text",
                    "text": {"content": f"🤖 Generated by AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}"},
                    "annotations": {"italic": True, "color": "gray"}
                }]
            }
        }
    ])
    
    payload = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "icon": {"emoji": "📖"},
        "properties": properties,
        "children": children
    }
    
    response = requests.post(
        NOTION_API_URL,
        headers=get_headers(),
        json=payload
    )
    
    if response.status_code != 200:
        raise Exception(f"Notion API error: {response.text}")
    
    return response.json()